# duplicated
root: / # root_urlpath
admin_dir: ecTrial/ # admin_route
tpl: /user_data/packages/default/ # front_urlpath
admin_tpl: /user_data/packages/admin/ # admin_urlpath
image_path: /upload/save_image/ # image_save_urlpath

# base valiables
root_dir: /var/www/ec_trial
root_urlpath: 
template_code: default

# routing
admin_route: ecTrial
user_data_route: user_data

# public directory
public_path: /html
public_path_realdir: /var/www/ec_trial/html

# realdir::image
image_save_realdir: /var/www/ec_trial/html/upload/save_image
image_temp_realdir: /var/www/ec_trial/html/upload/temp_image

# realdir::user_data
user_data_realdir: /var/www/ec_trial/html/user_data

# realdir::block
block_default_realdir: /var/www/ec_trial/src/Eccube/Resource/template/default/Block
block_realdir: /var/www/ec_trial/app/template/default/Block

# realdir::template
template_default_realdir: /var/www/ec_trial/src/Eccube/Resource/template/default
template_default_html_realdir: /var/www/ec_trial/html/template/default
template_admin_realdir: /var/www/ec_trial/src/Eccube/Resource/template/admin
template_admin_html_realdir: /var/www/ec_trial/html/template/admin
template_realdir: /var/www/ec_trial/app/template/default
template_html_realdir: /var/www/ec_trial/html/template/default
template_temp_realdir: /var/www/ec_trial/app/cache/eccube/template

# realdir::csv
csv_temp_realdir: /var/www/ec_trial/app/cache/eccube/csv

# realdir:plugin
plugin_realdir: /var/www/ec_trial/app/Plugin
plugin_temp_realdir: /var/www/ec_trial/app/cache/plugin
plugin_html_realdir: /var/www/ec_trial/html/plugin

# urlpath
admin_urlpath: /template/admin
front_urlpath: /template/default
image_save_urlpath: /upload/save_image
image_temp_urlpath: /upload/temp_image
user_data_urlpath: /user_data
plugin_urlpath: /plugin
